// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Permission struct {
	ID string `json:"id"`
}

type Role struct {
	ID          string   `json:"id"`
	Permissions []string `json:"permissions"`
}

type User struct {
	ID    string   `json:"id"`
	Roles []string `json:"roles"`
}
